---
- name: Run role
  hosts: all
  any_errors_fatal: true
- import_playbook: playbooks/00_system.yml
  tags:
  - system
#- import_playbook: playbooks/01_webserver.yml
#  tags:
#  - webserver
- import_playbook: playbooks/02_monitoring.yml
  tags:
  - monitoring
