
prometheus_targets:
  node:
  - targets:
      "{{ groups['all'] | map('extract', hostvars, ['inventory_hostname']) | map('regex_replace', '$', ':9100') | list }}"
    labels:
      env: demo
  alertmanager:
  - targets:
    - "{{ ansible_host | default(inventory_hostname) }}:9093"
    labels:
      env: demo
  random:
  - targets: "{{ random_exporter_addresses }}"


